export const STORAGE_KEY = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  SAVED_LOGIN: "SAVED_LOGIN",
  ACTIVE_MINUTES: "ACTIVE_MINUTES",
  ANDROID_DAILY_STEP: "ANDROID_DAILY_STEP",
  STAND_HOURS: "STAND_HOURS",
};