"""create health_analysis table

Revision ID: dc40e68648f0
Revises: 
Create Date: 2025-11-26 17:44:44.952030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc40e68648f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_image_url', sa.String(length=500), nullable=False),
    sa.Column('ai_diagnosis', sa.String(length=255), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('doctor_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_analysis')
    # ### end Alembic commands ###
